import './style.css';
import { buildPage } from './page';
import { todoApp } from './logic';

buildPage();
const app = todoApp();
app.newProjectInput();
app.newTaskInput();
app.readLocally();
app.addProject('Inbox');
app.selectProject('Inbox');
app.addProject('Exercise');
app.selectProject('Exercise');
app.addTask('Jog 20 minutes');
app.addProject('Work');
app.selectProject('Work');
app.addProject('Reading');
app.selectProject('Reading');
app.selectProject('Inbox');
app.addTask('Live and let die');
app.selectProject('Reading');
app.addTask('LOTR');
app.printAll();
app.storeLocally();
